DELIMITER $$
CREATE FUNCTION SprawdzNIP (nip VARCHAR(15))
RETURNS BIT
DETERMINISTIC
BEGIN
CREATE TEMPORARY TABLE waga
  (Pozycja INT AUTO_INCREMENT NOT NULL,
    Waga INT NOT NULL);
	INSERT INTO waga VALUES (6), (5), (7), (2), (3), (4), (5), (6), (7);
	IF SUBSTRING(nip, 10, 1) = (SELECT SUM(CONVERT(SUBSTRING(nip, Pozycja, 1), INT) * Waga) % 11 FROM waga) THEN
  RETURN 1;
      ELSE
      RETURN 0;
  	END IF;
END $$
DELIMITER ;
